name: Actions - Test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  actionlint:
    name: Actions - Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      # https://github.com/rhysd/actionlint/blob/main/.github/actionlint-matcher.json
      - name: Setup actionlint matcher
        run: echo "::add-matcher::.github/matchers/actionlint-matcher.json"

      - name: Actionlint
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color -verbose
